[package]
name = "web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "web"
path = "lib.rs"
doctest = false

[dependencies]
common.path = "../common"
log.path = "../log"
monitor_groups.path = "../monitor_groups"

axum.workspace = true
futures.workspace = true
http.workspace = true
httpdate.workspace = true
http-body.workspace = true
thiserror.workspace = true
pin-project.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
upon.workspace = true


[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
