[package]
name = "make"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "make"
path = "make.rs"
doctest = false

[dependencies]
xshell = "0.2.7"
